#!/bin/bash

count=1
total=$(ls OPEN_DATA_*.xml | wc -w)
output="OPEN_DATA_CFRC.xml" # CFRC: Canadian Federal Registered Corporations

for doc in $(ls OPEN_DATA_*.xml | sort -V); do
    if [ $count -eq 1 ]; then
	cat $doc | head -n -2 >> $output
    elif [ $count -eq $total ]; then
	cat $doc | tail -n +3 >> $output
    else
	cat $doc | tail -n +3 | head -n -2 >> $output
    fi
    count=$[$count + 1]
done
